---
- name: Verify
  hosts: all
  become: false
  gather_facts: false

  tasks:
  - name: Test connection
    ansible.builtin.ping:

  - name: Try the package module
    ansible.builtin.package:
      name: gzip
      state: present

  - name: Try the galen version
    ansible.builtin.command: |
      galen -v
    register: galenversion
